---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "choice.fullname" . }}
  labels:
    {{- include "choice.labels" . | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "choice.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "choice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: SERVER_PORT
            value: "8080"
          - name: SERVER_ADDRESS
            value: "0.0.0.0"
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
            value: 64MB
          - name: SPRING_SERVLET_MULTIPART_MAX_fILE_SIZE
            value: 64MB
          - name: SPRING_MAIN_LAZY_INITIALIZATION
            value: "true"
          - name: JAVA_OPTS
            value: -Xms128m -Xmx256m
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.postgres.username}}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.postgres.password}}
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://{{.Values.postgres.host}}:{{.Values.postgres.port}}/{{.Values.postgres.database}}
          - name: SPRING_JPA_HIBERNATE_HB2MDDL_AUTO
            value: {{.Values.hibernate.hb2mddl.auto}}
          - name: SPRING_JPA_GENERATE_DDL
            value: {{.Values.hibernate.generateDdl | quote}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_WISVCHCONNECT_ISSUER_URI
            value: {{.Values.oauth.issuer}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_WISVCHCONNECT_CLIENT_URI
            value: {{.Values.oauth.client.url}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_ID
            value: {{.Values.oauth.client.id}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_SECRET
            value: {{.Values.oauth.client.secret}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_SCOPE
            value: {{.Values.oauth.scope}}
          - name: WISVCH_CONNECT_ADMIN_GROUPS
            value: {{.Values.oauth.groups.admin}}
          - name: TZ
            value: Europe/Amsterdam
          resources:
            requests:
              cpu: 40m
              memory: 566M
            limits:
              cpu: 40m
              memory: 566M