---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feedback.fullname" . }}
  labels:
    {{- include "feedback.labels" . | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "feedback.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "feedback.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: SERVER_PORT
            value: "8080"
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/"
          - name: SERVER_ADDRESS
            value: "0.0.0.0"
          - name: SERVER_FORWARD_HEADERS_STRATEGY
            value: "native"
          - name: SPRING_MAIL_HOST
            value: {{.Values.mail.host}}
          - name: SPRING_MAIL_PORT
            value: {{.Values.mail.port | quote}}
          - name: SPRING_MAIL_USERNAME
            value: {{.Values.mail.username}}
          - name: SPRING_MAIL_PASSWORD
            value: {{.Values.mail.password}}
          - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
            value: {{ default "true" .Values.mail.auth | quote}}
          - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
            value: {{ default "true" .Values.mail.starttls | quote}}
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: JAVA_OPTS
            value: -Xms128m -Xmx256m
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.postgres.username}}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.postgres.password}}
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://{{.Values.postgres.host}}:{{.Values.postgres.port}}/{{.Values.postgres.database}}
          - name: SPRING_JPA_HIBERNATE_HB2MDDL_AUTO
            value: {{.Values.hibernate.hb2mddl.auto}}
          - name: SPRING_JPA_GENERATE_DDL
            value: {{.Values.hibernate.generateDdl | quote}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_WISVCHCONNECT_ISSUER_URI
            value: {{.Values.oauth.issuer}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_WISVCHCONNECT_CLIENTURI
            value: {{.Values.oauth.client.url}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_ID
            value: {{.Values.oauth.client.id}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_SECRET
            value: {{.Values.oauth.client.secret}}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_SCOPE
            value: {{.Values.oauth.scope}}
          - name: WISVCH_RECAPTCHA_VERIFYURI
            value: https://www.google.com/recaptcha/api/siteverify
          - name: WISVCH_RECAPTCHA_SITE
            value: {{.Values.recaptcha.site}}
          - name: WISVCH_RECAPTCHA_SECRET
            value: {{.Values.recaptcha.secret}}
          - name: SPRING_FLYWAY_ENABLED
            value: {{.Values.flyway.enabled | quote}}
          - name: SPRING_FLYWAY_SCHEMAS
            value: public
          - name: SPRING_FLYWAY_TABLE
            value: flyway_schema_history
          - name: TZ
            value: Europe/Amsterdam
          - name: WISVCH_CONNECT_ADMIN_GROUPS
            value: {{.Values.oauth.groups.admin}}
          - name: MAILNOTIFICATIONS_FROM
            value: {{.Values.mail.notifications.from}}
          - name: MAILNOTIFICATIONS_TO_ASSOCIATION
            value: {{.Values.mail.notifications.to.association}}
          - name: MAILNOTIFICATIONS_TO_EDUCATION
            value: {{.Values.mail.notifications.to.education}}
          - name: MAILNOTIFICATIONS_TO_EDUCATION_A_M
            value: {{.Values.mail.notifications.to.educationAM}}
          - name: MAILNOTIFICATIONS_TO_EDUCATION_C_S
            value: {{.Values.mail.notifications.to.educationCS}}
          resources:
            requests:
              cpu: 15m
              memory: 128M
            limits:
              memory: 392M