apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: listmonk-routes
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  - {{ .Values.domain }}
  rules:
  - matches:
    - path: 
        value: "/api/"
    - path: 
        value: "/admin/"
    - path:
        value: "/webhooks/bounce"
    backendRefs:
    - name: {{ include "listmonk.fullname" . }}-internal
      port: 80
  - matches:
    - path:
        value: "/archive.xml"
    - path: 
        value: "/subscription/"
    - path: 
        value: "/link/"
    - path: 
        value: "/campaign/"
    - path: 
        value: "/public/"
    - path: 
        value: "/webhooks/service/"
    - path: 
        value: "/api/public/"
    backendRefs:
    - name: {{ include "listmonk.fullname" . }}-external
      port: 80
