apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: listmonk-routes-internal
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
  hostnames:
  - {{ .Values.domain }}
  rules:
  - backendRefs:
    - name: {{ include "listmonk.fullname" . }}-internal
      port: 80
  - matches:
    - path: 
        value: "/api/"
    - path: 
        value: "/admin/"
    - path:
        value: "/webhooks/bounce"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: listmonk-routes-external
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
  hostnames:
  - {{ .Values.domain }}
  rules:
  - backendRefs:
    - name: {{ include "listmonk.fullname" . }}-external
      port: 80
  - matches:
    - path:
        PathMatchType : Exact
        value: /
    - path:
        PathMatchType: Exact
        value: /archive.xml
    - path: 
        value: "/subscription/"
    - path: 
        value: "/link/"
    - path: 
        value: "/campaign/"
    - path: 
        value: "/public/"
    - path: 
        value: "/webhooks/service/"
    - path: 
        value: /api/public/