---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "listmonk.fullname" . }}-internal
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/api/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-internal
                port:
                  name: http
          - pathType: Prefix
            path: "/admin/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-internal
                port:
                  name: http
          - pathType: Prefix
            path: "/webhooks/bounce"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-internal
                port:
                  name: http
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.tlsSecret }}
  {{- end}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "listmonk.fullname" . }}-public
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Exact
            path: /
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: "/subscription/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: "/link/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: "/campaign/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: "/public/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: "/archive"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Exact
            path: /archive.xml
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: "/webhooks/service/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
          - pathType: Prefix
            path: /api/public/
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}-external
                port:
                  name: http
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.tlsSecret }}
  {{- end}}