---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "listmonk.fullname" . }}-admin
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.authDomain }}/oauth2/auth{{- printf "?allowed_groups=%s"  (join "," .Values.allowedGroups) }}"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.authDomain }}/oauth2/start?rd=https://{{ .Values.domain }}$escaped_request_uri"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/api/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
          - pathType: Prefix
            path: "/admin/"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
          - pathType: Prefix
            path: "/webhooks/bounce"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.tlsSecret }}
  {{- end}}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "listmonk.fullname" . }}-public
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/subscription/*"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
          - pathType: Prefix
            path: "/link/*"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
          - pathType: Prefix
            path: "/campaign/*"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
          - pathType: Prefix
            path: "/public/*"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
          - pathType: Prefix
            path: "/webhooks/service/*"
            backend:
              service:
                name: {{ include "listmonk.fullname" $ }}
                port:
                  name: http
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.tlsSecret }}
  {{- end}}