{{ if .Values.postgres.initOrUpgradeTables }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "listmonk.fullname" . }}-init
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        {{- include "listmonk.selectorLabels" . | nindent 8 }}
        job: "upgrade-db"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      {{- if eq .Values.postgres.cloudSQL true }}
      initContainers:
      - name: cloud-sql-proxy
        image: {{ .Values.postgres.cloudSQLProxy.image | quote }}
        restartPolicy: Always
        args:
          - "--auto-iam-authn"
          - "--structured-logs"
          - "--private-ip"
          - "--port={{ .Values.postgres.port }}"
          - {{ .Values.postgres.cloudSQLProxy.instanceConnectionName | quote }}
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi
      {{- end }}
      containers:
      - name: upgrade-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["./listmonk", "--upgrade", "--yes"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: LISTMONK_db__host
            value: {{ .Values.postgres.host }}
          - name: LISTMONK_db__port
            value: {{ .Values.postgres.port | quote }}
          - name: LISTMONK_db__user
            value: {{ .Values.postgres.user }}
          - name: LISTMONK_db__password
            value: {{ .Values.postgres.password }}
          - name: LISTMONK_db__database
            value: {{ .Values.postgres.name }}
          - name: LISTMONK_db__ssl_mode
            value: disable

{{ end }}
