apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "listmonk.fullname" . }}
  labels:
    app: {{ include "listmonk.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi