apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "listmonk.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: {{ include "listmonk.fullname" . }}-pvc
  resources:
    requests:
      storage: 1Gi