---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "areafiftylan-legacy.fullname" . }}-admin
  labels:
    {{- include "areafiftylan-legacy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "admin"
      {{- include "areafiftylan-legacy.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "admin"
        {{- include "areafiftylan-legacy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.admin.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}