---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "areafiftylan-legacy.fullname" . }}-admin
  labels:
    app.kubernetes.io/component: "admin"
    {{- include "areafiftylan-legacy.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.admin.service.type | quote }}
  ports:
    - name: http
      protocol: TCP
      port: {{ default 80 .Values.admin.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: "admin"
    {{- include "areafiftylan-legacy.selectorLabels" . | nindent 4 }}