replicaCount: 1
image:
  repository: ghcr.io/wisvch/mand
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

auth:
  url: https://connect.ch.tudelft.nl
  clientId: mand
  clientSecret: ""

mand:
  allowedGroup: mand
  redirect: https://wisv.ch/admin/
  emptyRedirect: https://ch.tudelft.nl/
  notFoundRedirect: https://ch.tudelft.nl/404

postgres:
  username: ""
  password: ""
  name: mand
  host: ""
  port: 5432

domains:
  - wisv.ch

resources:
  requests:
    cpu: 50m
    memory: 100Mi