replicaCount: 1
serviceAccountName: default
image:
  repository: ghcr.io/wisvch/mand
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

auth:
  url: https://connect.ch.tudelft.nl
  clientId: mand
  clientSecret: ""

mand:
  allowedGroup: mand
  redirect: https://wisv.ch/admin/
  emptyRedirect: https://ch.tudelft.nl/
  notFoundRedirect: https://ch.tudelft.nl/404

postgres:
  username: ""
  password: ""
  name: mand
  host: ""
  port: 5432
  sslmode: disable
  cloudSQL: false
  cloudSQLProxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    instanceConnectionName: wisvch:europe-west4:geurt

domains:
  - wisv.ch

resources:
  requests:
    cpu: 50m
    memory: 100Mi
