defaultEdition: "2022"
fullnameOverride: ""

tlsSecret: ""
domains:
  - hackdelft.nl
  - hackdelft.com

editions:
  2022:
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/hackdelft-2022
      tag: 20220502-6dd5cd2
      pullPolicy: IfNotPresent
      pullSecrets: {}
  2019:
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: quay.io/wisvch/hackdelft-2019
      tag: 61
      pullPolicy: IfNotPresent
      pullSecrets: {}
  2018:
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: quay.io/wisvch/hackdelft-2018
      tag: 75
      pullPolicy: IfNotPresent
      pullSecrets: {}
  2017:
    replicaCount: 1
    containerPort: 3000
    service:
      type: ClusterIP
      port: 80
    image:
      repository: quay.io/wisvch/hackdelft-2017
      tag: 41
      pullPolicy: IfNotPresent
      pullSecrets: {}
