apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "static-site.fullname" . }}
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - {{ . }}
  {{- end }}
  rules:
    backendRefs:
    - name: {{ include "static-site.fullname" . }}
      port: {{ default 80 .Values.service.port }}
