---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-site.fullname" . }}
spec:
  rules:
  {{- if $.Values.domain}}
  {{- range $domain := .Values.domains}}
    - host: {{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "static-site.fullname" $ }}-{{ $domain | replace "." "-" }}
                port:
                  name: http
    {{- end }}
  {{- if $.Values.tlsSecret }}
  tls:
  - hosts:
    {{- range $domain := $.Values.domains}}
      - {{ $domain }}
    {{- end }}
    secretName: {{ $.Values.tlsSecret }}
  {{- end}}
  {{- else}}
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "static-site.fullname" $ }}
                port:
                  name: http
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.tlsSecret }}
  {{- end}}
  {{- end}}
