---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "areafiftylan-legacy.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
    {{- range $domain := .Values.domains}}
    - host: {{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "areafiftylan-legacy.fullname" $ }}-frontend
                port:
                  name: http
    - host: api.{{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "areafiftylan-legacy.fullname" $ }}-api
                port:
                  name: http
    - host: classified.{{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "areafiftylan-legacy.fullname" $ }}-admin
                port:
                  name: http
    {{- end }}
  {{- if .Values.tlsSecret }}
  tls:
  - hosts:
    {{- range $domain := .Values.domains}}
      - {{ $domain }}
      - api.{{ $domain }}
      - classified.{{ $domain }}
    {{- end }}
    secretName: {{ .Values.tlsSecret }}
  {{- end}}
