apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "areafiftylan-legacy.fullname" $ }}-frontend
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - {{ . }}
  {{- end }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "areafiftylan-legacy.fullname" $ }}
      port: {{ default 80 .Values.frontend.service.port }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "areafiftylan-legacy.fullname" $ }}-api
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - api.{{ . }}
  {{- end }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "areafiftylan-legacy.fullname" $ }}
      port: {{ default 80 .Values.api.service.port }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "areafiftylan-legacy.fullname" $ }}-admin
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - classified.{{ . }}
  {{- end }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "areafiftylan-legacy.fullname" $ }}
      port: {{ default 80 .Values.admin.service.port }}

