{{- if .Values.domains }}
{{- range .Values.domains}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "archive.fullname" $ }}-{{ . | replace "." "-" }}
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
    - {{ . }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "archive.fullname" $ }}
      port: {{ default 80 $.Values.service.port }}
{{- end }}
{{- end }}

