---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "archive.fullname" . }}
spec:
  rules:
  {{- range $key, $ingress := .Values.ingress}}
  {{- range $ingress.domains}}
    - host: {{ $key }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "archive.fullname" $ }}
                port:
                  name: http
  {{- end }}
  {{- end }}
  {{- range $key, $ingress := .Values.ingress}}
  {{- if $ingress.tlsSecret }}
  tls:
  - hosts:
    {{- range $ingress.domains}}
      - {{ . }}
    {{- end }}
    secretName: {{ $ingress.tlsSecret }}
  {{- end}}
  {{- end }}
