---
apiVersion: v1
kind: Service
metadata:
  name: { { include "wiki.fullname" . } }
  labels: { { - include "wiki.labels" . | nindent 4 } }
spec:
  type: { { default "ClusterIP" .Values.service.type | quote } }
  ports:
    - name: http
      protocol: TCP
      port: { { default 80 .Values.service.port } }
      targetPort: http
  selector: { { - include "wiki.selectorLabels" . | nindent 4 } }
