apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wiki.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi