apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi