replicaCount: 1
image:
  repository: lscr.io/linuxserver/piwigo
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: ""

service:
  type: ClusterIP
  port: 80

domain: flitcie.wisv.ch
authDomain: authproxy.wisv.ch
tlsSecret: 
