fullnameOverride: ""
replicaCount: 1

domain: wiki.wisv.ch

tlsSecret: ""

image:
  repository: ghcr.io/wisvch/wiki
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

connect2:
  host: connect2:80

iap:
  expected_audience: ""
