{{- range $key, $val := .Values.editions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hackdelft.fullname" $ }}-{{ $key }}
  labels:
    {{- include "hackdelft.labels" (merge (dict "edition" $key) $) | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "hackdelft.selectorLabels" (merge (dict "edition" $key) $) | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "hackdelft.selectorLabels" (merge (dict "edition" $key) $) | nindent 8 }}
    spec:
      {{- with .image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $key }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- end }}