apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hackdelft.fullname" . }}
spec:
  rules:
    {{- range $domain := .Values.domains}}
    - host: {{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "hackdelft.fullname" $ }}-{{ $.Values.defaultEdition }}
                port:
                  name: http
    {{- end }}
    {{- range $key, $val := .Values.editions }}
    {{- range $domain := $.Values.domains}}
    - host: {{ $key }}.{{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "hackdelft.fullname" $ }}-{{ $key }}
                port:
                  name: http
    {{- end }}
    {{- end }}
  {{- if $.Values.tlsSecret }}
  tls:
  - hosts:
    {{- range $domain := $.Values.domains}}
      - {{ $domain }}
    {{- end }}
    {{- range $key, $val := .Values.editions }}
    {{- range $domain := $.Values.domains}}
      - {{ $key }}.{{ $domain }}
    {{- end }}
    {{- end }}
    secretName: {{ $.Values.tlsSecret }}
  {{- end}}
