apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "hackdelft.fullname" . }}
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - {{ . }}
  {{- end }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "hackdelft.fullname" $ }}-{{ $.Values.defaultEdition }}
      port: 
        name: http
{{- range $key, $val := .Values.editions }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "hackdelft.fullname" $ }}-{{ $key }}
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range $domain := $.Values.domains}}
    - {{ $key }}.{{ $domain }}
  {{- end }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "hackdelft.fullname" $ }}-{{ $key }}
      port: 
        name: http
{{- end }}

