---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "areafiftylan.fullname" . }}
spec:
  rules:
    {{- range $domain := .Values.domains}}
    - host: {{ $domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "areafiftylan.fullname" $ }}
                port:
                  name: http
    {{- end }}