apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "areafiftylan.fullname" . }}
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - {{ . }}
  {{- end }}
  rules:
  - matches:
    backendRefs:
    - name: {{ include "areafiftylan.fullname" $ }}
      port: {{ default 80 .Values.service.port }}