apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flitcie.fullname" . }}
  labels:
    {{- include "flitcie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "flitcie.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flitcie.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /gallery
              name: flitcie-media
            - mountPath: /config
              name: flitcie-appdata
      {{- if eq .Values.mysql.cloudSQL true }}
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0
          args:
            - "--structured-logs"
            - "--private-ip"
            - "--port={{.Values.mysql.port}}"
            - "-i" # Enables automatic authentication through the serviceaccount
            - "wisvch:europe-west4:cluster-mysql-db"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 10Mi
        {{- end}}
      volumes:
        - name: flitcie-media
          persistentVolumeClaim:
            claimName: {{ include "flitcie.fullname" . }}-media
        - name: flitcie-appdata
          persistentVolumeClaim:
            claimName: {{ include "flitcie.fullname" . }}-appdata
    
