apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flitcie.fullname" . }}
  labels:
    {{- include "flitcie.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "flitcie.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flitcie.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: Europe/Amsterdam
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
          - mountPath: /gallery
            name: flitcie-media
          - mountPath: /config
            name: flitcie-appdata
      volumes:
        - name: flitcie-media
          persistentVolumeClaim:
            claimName: {{ include "flitcie.fullname" . }}-media
        - name: flitcie-appdata
          persistentVolumeClaim:
            claimName: {{ include "flitcie.fullname" . }}-appdata