apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flitcie.fullname" . }}-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 200Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flitcie.fullname" . }}-appdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi