fullnameOverride: ""

ingress:
  transip:
    domains:
      - lustrum.ch
      - eerstejaarsweekend.nl
    tlsSecret: staticsites-tls
  tudelft:
    domains:
      - symposium.ch.tudelft.nl
      - coh.ewi.tudelft.nl
      - commissies.ch.tudelft.nl
      - icpc.tudelft.nl
    tlsSecret: tudelft-tls

replicaCount: 1
containerPort: 8080
service:
  type: ClusterIP
  port: 80
image:
  repository: "ghcr.io/wisvch/archive"
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}
