fullnameOverride: ""

replicaCount: 1
containerPort: 8080
service:
  type: ClusterIP
  port: 80
image:
  repository: "ghcr.io/wisvch/archive"
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}
