fullnameOverride: ""

tlsSecret: ""
domains: 
  - symposium.ch.tudelft.nl
  - eerstejaarsweekend.nl
  - coh.ewi.tudelft.nl
  - commissies.ch.tudelft.nl

replicaCount: 1
containerPort: 8080
service:
  type: ClusterIP
  port: 80
image:
  repository: "ghcr.io/wisvch/archive"
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}
