fullnameOverride: ""
replicaCount: 1

domains:
  - areafiftylan.nl

service:
  type: ClusterIP
  port: 80

image:
  repository: ghcr.io/areafiftylan/areafiftylan
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}
