fullnameOverride: ""
replicaCount: 1

tlsSecret: ""
domains:
  - areafiftylan.nl

service:
  type: ClusterIP
  port: 80

image:
  repository: ghcr.io/areafiftylan/areafiftylan
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

postgres:
  username: areafiftylan
  password: areafiftylan
  database: areafiftylan
  host: postgres
  port: 5432
