apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki2.fullname" . }}
  labels:
    {{- include "wiki2.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "ch-iap-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    run: wiki2