fullnameOverride: ""
replicaCount: 1

service:
  type: ClusterIP
  port: 80

image:
  repository: ghcr.io/wisvch/choice
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

hibernate:
  generateDdl: false
  hb2mddl:
    auto: validate

postgres:
  username: ""
  password: ""
  host: ""
  port: 5432
  database: choice
