fullnameOverride: ""
replicaCount: 1

domain: choice.wisv.ch

tlsSecret: ""

service:
  type: ClusterIP
  port: 80

image:
  repository: ghcr.io/wisvch/choice
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}


hibernate:
  generateDdl: false
  hb2mddl:
    auto: validate

oauth:
  issuer: https://connect.ch.tudelft.nl
  client:
    url: https://choice.wisv.ch/login/oauth2/code/wisvchconnect
    id: choice-dashboard
    secret: ""
  scope: openid, profile, email, auth
  groups:
    admin: chbeheer,dienst2,epa,vc

postgres:
  username: ""
  password: ""
  host: ""
  port: 5432
  database: choice

    
