fullnameOverride: ""
replicaCount: 1

domain: feedback.wisv.ch

tlsSecret: ""

service:
  type: ClusterIP
  port: 80

image:
  repository: ghcr.io/wisvch/feedback
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

hibernate:
  generateDdl: false
  hb2mddl:
    auto: validate

oauth:
  issuer: https://connect.ch.tudelft.nl
  client:
    url: https://feedback.wisv.ch
    id: feedback-tool
    secret: ""
  groups: 
    admin: chbeheer, bestuur, vc



mail:
  host: ch.tudelft.nl
  port: 587
  username: ""
  password: ""
  auth: true
  starttls: false
  notifications:
    from: noreply@ch.tudelft.nl
    to:
      association: bestuur@ch.tudelft.nl
      education: education@ch.tudelft.nl
      educationAM: cow@ch.tudelft.nl
      educationCS: coi@ch.tudelft.nl

postgres:
  username: ""
  password: ""
  host: ""
  port: 5432
  database: feedback

recaptcha:
  site: ""
  secret: ""

flyway:
  enabled: true

    
