---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "events.fullname" . }}
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/events"
            backend:
              service:
                name: {{ include "events.fullname" $ }}
                port:
                  name: http