---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "areafiftylan-legacy.fullname" . }}-api
  labels:
    {{- include "areafiftylan-legacy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "api"
      {{- include "areafiftylan-legacy.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "api"
        {{- include "areafiftylan-legacy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/management/health
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/v1/management/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
          - name: JAVA_OPTS
            value: -Xms64m -Xmx192m
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: SERVER_PORT
            value: "8080"
          - name: SPRING_MAIL_HOST
            value: {{ .Values.mail.host }}
          - name: SPRING_MAIL_PORT
            value: {{ .Values.mail.port | quote }}
          - name: SPRING_MAIL_USERNAME
            value: {{ .Values.mail.username }}
          - name: SPRING_MAIL_PASSWORD
            value: {{ .Values.mail.password }}
          - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
            value: {{ .Values.mail.auth | quote }}
          - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
            value: {{ .Values.mail.starttls | quote }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.postgres.username }}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
          - name: A5L_MOLLIEKEY
            value: {{ .Values.mollie.key }}
          - name: A5L_GOOGLEMAPSAPIKEY
            value: {{ .Values.gmaps.key }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}