fullnameOverride: ""
replicaCount: 1

domain: dienst2.ch.tudelft.nl

image:
  repository: ghcr.io/wisvch/dienst2
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

allowedHosts: "*"

cache:
  url: locmemcache://
iap:
  expected_audience: ""

postgres:
  username: ""
  password: ""
  host: ""
  port: 5432
  database: dienst2
  cloudSQL: true

secret_key: ""

serviceAccountSecretName: ""
serviceAccountSecretKey: ""
