fullnameOverride: ""
replicaCount: 1

image:
  repository: ghcr.io/wisvch/dienst2
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

iap:
  expected_audience: ""

postgres:
  username: ""
  password: ""
  host: ""
  port: 5432
  database: events
  cloudSQL: true
