apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "mand.fullname" . }}
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  {{- range .Values.domains}}
    - {{ . }}
  {{- end }}
  rules:
  - matches:
    - path: 
        value: "/admin"
    - path:
        value: "/link/"
    backendRefs:
    - name: {{ include "mand.fullname" . }}-internal
      port: 80
  - matches:
    - path:
        value: "/"
    backendRefs:
    - name: {{ include "mand.fullname" . }}-external
      port: 80
