---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connect2.fullname" . }}
  labels:
    {{- include "connect2.labels" . | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "connect2.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "connect2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: service-account-key
          secret:
            secretName: {{ .Values.serviceAccountSecretName }}
            items: 
              - key: {{ .Values.serviceAccountSecretKey }}
                path: key.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/key.json
          volumeMounts:
            - mountPath: /secret/key.json
              name: service-account-key
              subPath: key.json
              readOnly: true
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
        