---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "connect2.fullname" . }}
  labels:
    {{- include "connect2.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type | quote }}
  ports:
    - name: http
      protocol: TCP
      port: {{ default 80 .Values.service.port }}
      targetPort: http
  selector:
    {{- include "connect2.selectorLabels" . | nindent 4 }}