fullnameOverride: ""
replicaCount: 1

domain: events.wisv.ch

tlsSecret: ""

service:
  type: ClusterIP
  port: 80

image:
  repository: ghcr.io/wisvch/events
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: {}

mail:
  host: ch.tudelft.nl
  port: 25
  username: ""
  password: ""

hibernate:
  generateDdl: false
  hb2mddl:
    auto: validate

oauth:
  issuer: https://connect.ch.tudelft.nl
  client:
    url: https://ch.tudelft.nl/events
    id: events-cloud
    secret: ""
  scope: openid, profile, email, auth
  claimName: google_groups
  groups:
    admin: chbeheer,dienst2,epa,vc
    beta: joepj, juliand
links:
  gtc: "https://ch.tudelft.nl/wp-content/uploads/Deelnemersvoorwaarden_versie_12_06_2023.pdf" 
mollie:
  key: ""

flyway:
  enabled: true

postgres:
  username: ""
  password: ""
  host: ""
  port: 5432
  database: events
  cloudSQL: true
