fullnameOverride: ""

tlsSecret: ""
domains:
  - areafiftylan.nl
  - areafiftylan.com

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/areafiftylan/lancie-frontend
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: {}
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
